import { scryptSync, timingSafeEqual } from "node:crypto";

export interface AppAuthConfig {
  username: string;
  /** `scrypt$<saltHex>$<hashHex>`, generated by scripts/hash-admin-password.mjs. */
  passwordHash: string;
}

export interface AppAuthUseCases {
  verifyCredentials(username: string, password: string): boolean;
}

const SCRYPT_KEY_LENGTH = 64;

export function createAppAuthUseCases(config: AppAuthConfig): AppAuthUseCases {
  const [scheme, saltHex, hashHex] = config.passwordHash.split("$");
  if (scheme !== "scrypt" || !saltHex || !hashHex) {
    throw new Error("APP_ADMIN_PASSWORD_HASH must be in scrypt$<salt>$<hash> form (see scripts/hash-admin-password.mjs)");
  }
  const salt = Buffer.from(saltHex, "hex");
  const expectedHash = Buffer.from(hashHex, "hex");

  return {
    verifyCredentials(username, password) {
      if (username !== config.username) return false;
      const candidateHash = scryptSync(password, salt, SCRYPT_KEY_LENGTH);
      return candidateHash.length === expectedHash.length && timingSafeEqual(candidateHash, expectedHash);
    },
  };
}
